### ISSUE TITLE
Support PWA

### ISSUE THREAD

**Issue by longhoang0304** [longhoang0304/sudoku#1]
# Description
- Add PWA support for the current application

# Todo
- [ ] Add app.mantifest
- [ ] Add service worker
- [ ] Cache all HTML, JS, Assets files from service worker
- [ ] Support offline
